# Generated by Django 5.2.3 on 2025-11-11 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='processing_jobs/')),
                ('job_type', models.CharField(choices=[('expiry', 'Expiry Date'), ('ingredient', 'Ingredient ID')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('detected_text', models.TextField(blank=True)),
                ('processed_data', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('prep_time', models.IntegerField(blank=True, null=True)),
                ('cook_time', models.IntegerField(blank=True, null=True)),
                ('cuisine', models.CharField(choices=[('kenyan', 'Kenyan'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('asian', 'Asian'), ('indian', 'Indian'), ('mediterranean', 'Mediterranean'), ('american', 'American'), ('french', 'French'), ('thai', 'Thai'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('other', 'Other')], max_length=50)),
                ('servings', models.IntegerField()),
                ('instructions', models.TextField()),
                ('total_calories', models.FloatField(blank=True, null=True)),
                ('total_protein', models.FloatField(blank=True, null=True)),
                ('total_carbs', models.FloatField(blank=True, null=True)),
                ('total_fat', models.FloatField(blank=True, null=True)),
                ('dietary_tags', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('average_rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Weekly Shopping List', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'AI Generated'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pantry_utilization', models.FloatField(default=0)),
                ('goal_alignment', models.FloatField(default=0)),
                ('waste_reduction_score', models.FloatField(default=0)),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy & Eggs'), ('meat', 'Meat & Poultry'), ('seafood', 'Seafood'), ('grains', 'Grains & Cereals'), ('legumes', 'Legumes & Nuts'), ('spices', 'Spices & Herbs'), ('condiments', 'Condiments & Sauces'), ('beverages', 'Beverages'), ('frozen', 'Frozen Foods'), ('bakery', 'Bakery'), ('canned', 'Canned Goods'), ('other', 'Other')], default='other', max_length=50)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='g', max_length=20)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=20)),
                ('purchased', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shoppinglist')),
            ],
            options={
                'ordering': ['priority', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='UserPantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy & Eggs'), ('meat', 'Meat & Poultry'), ('seafood', 'Seafood'), ('grains', 'Grains & Cereals'), ('legumes', 'Legumes & Nuts'), ('spices', 'Spices & Herbs'), ('condiments', 'Condiments & Sauces'), ('beverages', 'Beverages'), ('frozen', 'Frozen Foods'), ('bakery', 'Bakery'), ('canned', 'Canned Goods'), ('other', 'Other')], default='other', max_length=50)),
                ('calories', models.FloatField(default=0, help_text='Calories per 100g')),
                ('protein', models.FloatField(default=0, help_text='Protein in grams per 100g')),
                ('carbs', models.FloatField(default=0, help_text='Carbohydrates in grams per 100g')),
                ('fat', models.FloatField(default=0, help_text='Fat in grams per 100g')),
                ('fiber', models.FloatField(default=0, help_text='Fiber in grams per 100g')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='g', max_length=20)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('typical_expiry_days', models.IntegerField(blank=True, null=True)),
                ('storage_instructions', models.TextField(blank=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='pantry_images/')),
                ('expiry_label_image', models.ImageField(blank=True, null=True, upload_to='expiry_labels/')),
                ('detected_expiry_text', models.TextField(blank=True)),
                ('detection_confidence', models.FloatField(blank=True, null=True)),
                ('detection_source', models.CharField(choices=[('manual', 'Manual Entry'), ('vision_api', 'Google Vision API'), ('barcode', 'Barcode Scan')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('wasted', 'Wasted'), ('expired', 'Expired')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User pantries',
                'ordering': ['expiry_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='g', max_length=50)),
                ('optional', models.BooleanField(default=False, help_text='Whether ingredient is optional')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe')),
                ('pantry_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userpantry')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes_used_in', through='core.RecipeIngredient', to='core.userpantry'),
        ),
        migrations.CreateModel(
            name='FoodWasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_quantity', models.FloatField()),
                ('quantity_wasted', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('over_purchased', 'Over Purchased'), ('didnt_like', "Didn't Like"), ('recipe_change', 'Recipe Changed'), ('forgot_about', 'Forgot About It'), ('other', 'Other')], max_length=50)),
                ('reason_details', models.TextField(blank=True)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('waste_date', models.DateField(auto_now_add=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pantry_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userpantry')),
            ],
            options={
                'ordering': ['-waste_date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('KES', 'KES')], default='USD', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'active'], name='core_budget_user_id_98c77d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'status'], name='core_shoppi_user_id_9b6d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['year', 'week_number'], name='core_shoppi_year_298de5_idx'),
        ),
        migrations.AddIndex(
            model_name='userpantry',
            index=models.Index(fields=['user', 'status'], name='core_userpa_user_id_218742_idx'),
        ),
        migrations.AddIndex(
            model_name='userpantry',
            index=models.Index(fields=['expiry_date'], name='core_userpa_expiry__3b0bab_idx'),
        ),
        migrations.AddIndex(
            model_name='userpantry',
            index=models.Index(fields=['user', 'expiry_date'], name='core_userpa_user_id_3baf36_idx'),
        ),
        migrations.AddIndex(
            model_name='userpantry',
            index=models.Index(fields=['user', 'category'], name='core_userpa_user_id_d54b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='userpantry',
            index=models.Index(fields=['name'], name='core_userpa_name_e40938_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['cuisine'], name='core_recipe_cuisine_e990f2_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty'], name='core_recipe_difficu_0ca800_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['average_rating'], name='core_recipe_average_50d158_idx'),
        ),
        migrations.AddIndex(
            model_name='foodwasterecord',
            index=models.Index(fields=['user', 'waste_date'], name='core_foodwa_user_id_477233_idx'),
        ),
    ]
