# Generated by Django 5.2.3 on 2025-10-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('kenyan', 'Kenyan'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('asian', 'Asian'), ('indian', 'Indian'), ('mediterranean', 'Mediterranean'), ('american', 'American'), ('french', 'French'), ('thai', 'Thai'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('other', 'Other')], max_length=50),
        ),
    ]
