# Generated by Django 5.2.3 on 2025-10-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='common_units',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='nutritional_info',
            field=models.CharField(max_length=200),
        ),
    ]
