# Generated by Django 5.2.3 on 2025-10-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_recipe_cook_time_alter_recipe_prep_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGoal',
        ),
    ]
