# Generated by Django 5.2.3 on 2025-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ingredient_common_units_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipe',
            name='core_recipe_dietary_55fb9b_idx',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dietary_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutritional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
