# Generated by Django 5.2.3 on 2025-10-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_recipe_core_recipe_dietary_55fb9b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nutritional_info',
            field=models.TextField(max_length=200),
        ),
    ]
