# Generated by Django 5.2.3 on 2025-10-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredient_user_delete_consumptionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
    ]
