# Generated by Django 5.2.3 on 2025-10-23 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('build_muscle', 'Build Muscle'), ('maintain_weight', 'Maintain Weight'), ('more_fiber', 'More Fiber'), ('more_iron', 'More Iron'), ('more_veggies', 'More Vegetables'), ('reduce_waste', 'Reduce Food Waste'), ('budget_friendly', 'Budget Friendly')], max_length=20)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
