# Generated by Django 5.2.3 on 2025-10-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_budget_amount_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='disliked_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_cuisines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
