# Generated by Django 5.2.3 on 2025-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_disliked_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='List of food allergies (comma-separated or JSON string)', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='Dietary preferences e.g. vegetarian, vegan, gluten-free', null=True),
        ),
    ]
