# Generated by Django 5.2.3 on 2025-10-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
