# Generated by Django 5.2.3 on 2025-10-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
